# Dockerfile.frontend
FROM node:22-alpine

WORKDIR /app/frontend

# Copy package files trước để tận dụng cache
COPY frontend/package*.json ./

RUN npm install

# Copy source code
COPY frontend/ .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]