events {}

http {
    upstream fastapi {
        server api:8000;
    }

    server {
        listen 80;
        server_name suvitech.io.vn;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name suvitech.io.vn;

        ssl_certificate /etc/letsencrypt/live/suvitech.io.vn/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/suvitech.io.vn/privkey.pem;

        location / {
            proxy_pass http://fastapi;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_buffering off;
        }
    }
}