events {}

http {
    server {
        listen 80;
        server_name suvitech.io.vn;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 200 "He thong dang khoi tao SSL, vui long doi giay lat va F5...";
        }
    }
}