dataset_path: data/pages.json

chunking:
  type: enrich_hybrid
  chunk_size: 500
  overlap: 50
  embedder: BAAI/bge-m3
  queries_col_name: hybrid_queries
  qrels_col_name: hybrid_qrels

embedding:
  col_name: enrich_hybrid_collection
  model: BAAI/bge-m3

vectorstore:
  type: qdrant
  path: data/vector_index

generator:
  provider: openai
  model: gpt-4o-mini
  temperature: 0