chunking:
  type: semantic
  chunk_size: 500
  overlap: 50
  embedder: BAAI/bge-m3
  tokenizer: gpt-5-nano
  chunk_col_name: semantic_chunks #eval

evaluation:
  qrels_col_name: qrels #eval
  queries_col_name: queries

embedding:
  vector_col_name: semantic_collecction
  model: BAAI/bge-m3